backend:
  name: github
  repo: karisakib/pixelprysm # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

site_url: https://pixelprysm.com
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
media_folder: "static/images/uploads"
media_library:
  name: uploadcare

collections:
  - name: blog
    label: Blog
    extension: "json"
    folder: content/blog
    media_folder: "static/images/uploads"
    media_library:
      name: blog_posts
    create: true
    slug: "{{title}}"
    filter: {field: visibleInCMS, value: true}
    fields:
      - {name: title, widget: string}
      - {name: slug, widget: string, pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Slug must only contain lowercase letters, numbers, and hyphens"], hint: "Auto-generated from title", default: "{{fields.title}}", required: true}
      - {name: description, widget: string}
      - {name: date, widget: datetime, date_format: "MMMM D, YYYY"}
      - {name: body, widget: markdown}
