backend:
  name: github
  repo: karisakib/pixelprysm # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)

collections:
  - name: blog
    label: Blog
    slug: {{slug}}
    folder: content/blog
    create: true
    filter: {field: visibleInCMS, value: true}
    fields: [
      {name: title, widget: string},
      {name: description, widget: string},
      {name: body, widget: markdown},
      {name: visibleInCMS, widget: hidden, default: true},
    ]
